site_name: cli-template
site_description: Yet another template.

repo_name: tygourm/cli-template
repo_url: https://github.com/tygourm/cli-template

theme:
  name: material

  features:
    - content.code.copy
    - navigation.footer
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.prune
    - navigation.top
    - navigation.tracking
    - search.share
    - search.suggest
    - toc.follow

  palette:
    # System palette
    - media: '(prefers-color-scheme)'
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Light palette
    - media: '(prefers-color-scheme: light)'
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Dark palette
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  font:
    text: Ubuntu
    code: Ubuntu Mono

  logo: img/terminal-solid.svg
  favicon: img/terminal-solid.svg
  icon:
    repo: fontawesome/brands/github

plugins:
  - offline
  - privacy
  - search

markdown_extensions:
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.inlinehilite
  - pymdownx.superfences

nav:
  - Home: README.md
  - Changelog: CHANGELOG.md
  - Release Engineering: RELENG.md

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css
